server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      fail-fast: true
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/books/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/loans/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/
