server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-server
              uri: lb://auth-server
              predicates:
                - Path=/oauth2/**, /login/**

            - id: book-service
              uri: lb://book-service
              predicates:
                - Path=/api/books/**
              filters:
                - name: AddRequestHeader
                  args:
                    name: Authorization
                    value: "Bearer {jwt}"
                - name: RewritePath
                  args:
                    regexp: "/api/books/(?<segment>.*)"
                    replacement: "/api/books/${segment}"

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - name: AddRequestHeader
                  args:
                    name: Authorization
                    value: "Bearer {jwt}"
                - name: RewritePath
                  args:
                    regexp: "/api/users/(?<segment>.*)"
                    replacement: "/api/users/${segment}"

            - id: loan-service
              uri: lb://loan-service
              predicates:
                - Path=/api/loans/**
              filters:
                - name: AddRequestHeader
                  args:
                    name: Authorization
                    value: "Bearer {jwt}"
                - name: RewritePath
                  args:
                    regexp: "/api/loans/(?<segment>.*)"
                    replacement: "/api/loans/${segment}"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO

