# server:
#   port: 9000

# spring:
#   application:
#     name: auth-server

# eureka:
#   client:
#     service-url:
#       defaultZone: http://discovery-server:8761/
server:
  port: 9000

spring:
  application:
    name: auth-server
  security:
    oauth2:
      authorization-server:
        issuer: http://auth-server:9000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

