server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://loan-db:5432/loandb
    username: loan_user
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: loan-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
